apiVersion: v1
kind: Service
metadata:
  labels:
    run: share
  name: share
  namespace: share
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: share
  type: LoadBalancer
